---
version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errchkjson
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - unparam
    - unused
  disable:
    - gofmt  # Handled by pre-commit hook
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: comment on exported (method|function|type|const|var)
    paths:
      - third_party$
      - builtin$
      - examples$
# Formatting handled by pre-commit hook (.git/hooks/pre-commit)
# golangci-lint only checks non-auto-fixable issues
