# Vulnerability Allowlist
# 
# This file documents known vulnerabilities that have been reviewed and
# determined to be non-exploitable in the VirtEngine context, or are
# accepted risks with appropriate mitigations.
#
# Each entry must include:
#   - id: CVE or GHSA identifier
#   - package: Affected package
#   - reason: Why this is allowlisted
#   - reviewed_by: GitHub username of reviewer
#   - reviewed_date: Date of review (YYYY-MM-DD)
#   - expires: Expiration date for this allowlist entry
#   - references: Links to relevant issues or documentation
#   - mitigations: Any mitigations in place
#
# Entries are automatically reviewed on expiration and must be renewed
# with updated justification.

version: 1
schema_version: "1.0.0"

# Go dependencies
go:
  allowlist: []
  # Example entry:
  # - id: CVE-2024-XXXXX
  #   package: github.com/example/package
  #   version: "< v1.2.3"
  #   reason: |
  #     This vulnerability requires specific conditions that are not
  #     present in our usage of this package. Specifically, we do not
  #     use the affected function in any code path.
  #   reviewed_by: security-team
  #   reviewed_date: "2024-01-15"
  #   expires: "2024-07-15"
  #   references:
  #     - https://github.com/virtengine/virtengine/issues/XXX
  #     - https://nvd.nist.gov/vuln/detail/CVE-2024-XXXXX
  #   mitigations:
  #     - Input validation prevents triggering condition
  #     - Rate limiting reduces exploitation impact

# Python dependencies (ML pipelines)
python:
  allowlist: []

# npm dependencies (Portal library)
npm:
  allowlist: []

# Container base images
containers:
  allowlist: []

# Configuration for vulnerability scanning
config:
  # Severity levels to block on (others are warnings)
  block_on:
    - CRITICAL
    - HIGH
  
  # Maximum age for allowlist entries (days)
  max_allowlist_age: 180
  
  # Require security team approval for allowlist additions
  require_approval: true
  
  # Automatically create issues for expiring allowlist entries
  auto_create_issues: true
  
  # Days before expiration to create reminder issue
  expiration_warning_days: 30

# Audit log of allowlist changes
audit_log:
  - date: "2024-01-01"
    action: "created"
    by: "security-team"
    description: "Initial vulnerability allowlist created"
