packages:
  - 'lib/portal'
  - 'lib/capture'
  - 'lib/admin'
  - 'portal'

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver
