# ArgoCD Project Definition for VirtEngine
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: virtengine
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: VirtEngine blockchain infrastructure project

  # Source repositories
  sourceRepos:
    - https://github.com/virtengine-network/virtengine.git
    - https://github.com/virtengine-network/virtengine-helm.git
    - https://charts.bitnami.com/bitnami
    - https://argoproj.github.io/argo-helm
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/aws-load-balancer-controller

  # Allowed destination clusters and namespaces
  destinations:
    # Dev cluster
    - namespace: '*'
      server: https://virtengine-dev.us-west-2.eks.amazonaws.com
    # Staging cluster
    - namespace: '*'
      server: https://virtengine-staging.us-west-2.eks.amazonaws.com
    # Production cluster (restricted namespaces)
    - namespace: virtengine
      server: https://virtengine-prod.us-west-2.eks.amazonaws.com
    - namespace: monitoring
      server: https://virtengine-prod.us-west-2.eks.amazonaws.com
    - namespace: external-secrets
      server: https://virtengine-prod.us-west-2.eks.amazonaws.com
    - namespace: istio-system
      server: https://virtengine-prod.us-west-2.eks.amazonaws.com
    - namespace: argocd
      server: https://virtengine-prod.us-west-2.eks.amazonaws.com
    # In-cluster for bootstrap
    - namespace: '*'
      server: https://kubernetes.default.svc

  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: networking.k8s.io
      kind: IngressClass
    - group: storage.k8s.io
      kind: StorageClass
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration

  # Namespace resource deny list (security)
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange

  # Sync windows for production (maintenance windows)
  syncWindows:
    # Allow syncs during maintenance window
    - kind: allow
      schedule: '0 2 * * 0'  # Sundays at 2 AM
      duration: 4h
      applications:
        - '*-prod'
      namespaces:
        - virtengine
      clusters:
        - https://virtengine-prod.us-west-2.eks.amazonaws.com
    # Deny syncs outside maintenance for prod (can be overridden manually)
    - kind: deny
      schedule: '0 6 * * *'  # Every day at 6 AM (after maintenance)
      duration: 20h
      applications:
        - '*-prod'
      manualSync: true  # Allow manual sync override

  # Role definitions
  roles:
    - name: dev-team
      description: Development team - full access to dev, read access elsewhere
      policies:
        - p, proj:virtengine:dev-team, applications, *, virtengine/*, allow
        - p, proj:virtengine:dev-team, applications, get, virtengine/*-staging, allow
        - p, proj:virtengine:dev-team, applications, get, virtengine/*-prod, allow
        - p, proj:virtengine:dev-team, logs, get, virtengine/*, allow
      groups:
        - virtengine-developers

    - name: sre-team
      description: SRE team - full access to all environments
      policies:
        - p, proj:virtengine:sre-team, applications, *, virtengine/*, allow
        - p, proj:virtengine:sre-team, logs, get, virtengine/*, allow
        - p, proj:virtengine:sre-team, exec, create, virtengine/*, allow
      groups:
        - virtengine-sre

    - name: readonly
      description: Read-only access for monitoring
      policies:
        - p, proj:virtengine:readonly, applications, get, virtengine/*, allow
        - p, proj:virtengine:readonly, logs, get, virtengine/*, allow
      groups:
        - virtengine-viewers

  # Orphaned resources monitoring
  orphanedResources:
    warn: true
    ignore:
      - group: ''
        kind: ConfigMap
        name: kube-root-ca.crt
