# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: virtengine/bme/v1/events.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'virtengine/bme/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from virtengine.bme.v1 import types_pb2 as virtengine_dot_bme_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1evirtengine/bme/v1/events.proto\x12\x11virtengine.bme.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x1dvirtengine/bme/v1/types.proto\"\xfb\x01\n\x15\x45ventMintStatusChange\x12\x46\n\x0fprevious_status\x18\x01 \x01(\x0e\x32\x1d.virtengine.bme.v1.MintStatusR\x0epreviousStatus\x12<\n\nnew_status\x18\x02 \x01(\x0e\x32\x1d.virtengine.bme.v1.MintStatusR\tnewStatus\x12\\\n\x10\x63ollateral_ratio\x18\x03 \x01(\tB1\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDec\xd2\xb4-\ncosmos.DecR\x0f\x63ollateralRatio\"\xb0\x01\n\x10\x45ventVaultSeeded\x12\x37\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06\x61mount\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\x12K\n\x11new_vault_balance\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x0fnewVaultBalance\"x\n\x19\x45ventLedgerRecordExecuted\x12[\n\x02id\x18\x01 \x01(\x0b\x32!.virtengine.bme.v1.LedgerRecordIDB(\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\x14yaml:\"burneidd_from\"R\x02idB5Z3github.com/virtengine/virtengine/sdk/go/node/bme/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'virtengine.bme.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/virtengine/virtengine/sdk/go/node/bme/v1'
  _globals['_EVENTMINTSTATUSCHANGE'].fields_by_name['collateral_ratio']._loaded_options = None
  _globals['_EVENTMINTSTATUSCHANGE'].fields_by_name['collateral_ratio']._serialized_options = b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec\322\264-\ncosmos.Dec'
  _globals['_EVENTVAULTSEEDED'].fields_by_name['amount']._loaded_options = None
  _globals['_EVENTVAULTSEEDED'].fields_by_name['amount']._serialized_options = b'\310\336\037\000'
  _globals['_EVENTVAULTSEEDED'].fields_by_name['new_vault_balance']._loaded_options = None
  _globals['_EVENTVAULTSEEDED'].fields_by_name['new_vault_balance']._serialized_options = b'\310\336\037\000'
  _globals['_EVENTLEDGERRECORDEXECUTED'].fields_by_name['id']._loaded_options = None
  _globals['_EVENTLEDGERRECORDEXECUTED'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\024yaml:\"burneidd_from\"'
  _globals['_EVENTMINTSTATUSCHANGE']._serialized_start=166
  _globals['_EVENTMINTSTATUSCHANGE']._serialized_end=417
  _globals['_EVENTVAULTSEEDED']._serialized_start=420
  _globals['_EVENTVAULTSEEDED']._serialized_end=596
  _globals['_EVENTLEDGERRECORDEXECUTED']._serialized_start=598
  _globals['_EVENTLEDGERRECORDEXECUTED']._serialized_end=718
# @@protoc_insertion_point(module_scope)
