---
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}_mock.go"
with-expecter: True
resolve-type-alias: False
dir: mocks
issue-845-fix: True
packages:
  github.com/virtengine/virtengine/sdk/go/node/client/v1beta3:
    config:
      dir: mocks/node/client
    interfaces:
      QueryClient:
      TxClient:
      NodeClient:
      LightClient:
      Client:
  github.com/virtengine/virtengine/sdk/go/node/audit/v1:
    config:
      dir: mocks/node/client/audit
    interfaces:
      QueryClient: {}
  github.com/virtengine/virtengine/sdk/go/node/cert/v1:
    config:
      dir: mocks/node/client/cert
    interfaces:
      QueryClient: {}
  github.com/virtengine/virtengine/sdk/go/node/deployment/v1beta4:
    config:
      dir: mocks/node/client/deployment
    interfaces:
      QueryClient: {}
  github.com/virtengine/virtengine/sdk/go/node/market/v1beta5:
    config:
      dir: mocks/node/client/market
    interfaces:
      QueryClient: {}
  github.com/virtengine/virtengine/sdk/go/node/provider/v1beta4:
    config:
      dir: mocks/node/client/provider
    interfaces:
      QueryClient: {}
