# Database Backup and Restore Runbook
# Procedures for CockroachDB backup, verification, and restoration

name: Database Backup and Restore
version: "1.0"

backup:
  schedule:
    full: "0 0 * * *"
    incremental: "0 */6 * * *"

  destinations:
    - region: us-east-1
      bucket: s3://virtengine-cockroachdb-backup-us-east-1/backups
    - region: eu-west-1
      bucket: s3://virtengine-cockroachdb-backup-eu-west-1/backups
    - region: ap-southeast-1
      bucket: s3://virtengine-cockroachdb-backup-ap-southeast-1/backups

  retention:
    full_backups: 30d
    incremental: 7d
    archived: 365d

  verification:
    schedule: "0 6 * * 1"
    steps:
      - name: list_backups
        command: |
          cockroach sql --certs-dir=/cockroach/cockroach-certs \
            -e "SHOW BACKUP LATEST IN 's3://virtengine-cockroachdb-backup-${REGION}/backups?AUTH=implicit';"

      - name: verify_backup_completeness
        command: |
          cockroach sql --certs-dir=/cockroach/cockroach-certs \
            -e "SHOW BACKUP LATEST IN 's3://virtengine-cockroachdb-backup-${REGION}/backups?AUTH=implicit' WITH check_files;"

restore:
  pre_checks:
    - name: confirm_target_empty
      description: "Ensure target cluster has no conflicting data"
      command: |
        cockroach sql --certs-dir=/cockroach/cockroach-certs \
          -e "SELECT count(*) FROM [SHOW DATABASES] WHERE database_name NOT IN ('system', 'defaultdb', 'postgres');"
      expect: "0"

    - name: verify_backup_source
      description: "Confirm backup source is valid"
      command: |
        cockroach sql --certs-dir=/cockroach/cockroach-certs \
          -e "SHOW BACKUP LATEST IN '${BACKUP_URI}';"

  steps:
    - name: stop_application
      description: "Scale down application workloads"
      command: |
        kubectl --context=${CONTEXT} -n virtengine scale deployment --all --replicas=0
      timeout: 2m

    - name: restore_database
      description: "Restore from backup"
      command: |
        cockroach sql --certs-dir=/cockroach/cockroach-certs \
          -e "RESTORE FROM LATEST IN '${BACKUP_URI}' WITH detached;"
      timeout: 30m

    - name: monitor_restore_progress
      description: "Monitor restore job progress"
      command: |
        cockroach sql --certs-dir=/cockroach/cockroach-certs \
          -e "SELECT job_id, status, fraction_completed, error FROM [SHOW JOBS] WHERE job_type = 'RESTORE' ORDER BY created DESC LIMIT 1;"
      poll_interval: 30s
      until: "status = 'succeeded'"
      timeout: 30m

    - name: verify_data_integrity
      description: "Run integrity checks on restored data"
      command: |
        cockroach sql --certs-dir=/cockroach/cockroach-certs \
          -e "SELECT database_name, table_name, status FROM [SHOW RANGES FROM DATABASE virtengine] WHERE status != 'valid';"
      expect: "0 rows"

    - name: restart_application
      description: "Scale up application workloads"
      command: |
        kubectl --context=${CONTEXT} -n virtengine scale deployment --all --replicas=3
      timeout: 5m

  post_checks:
    - name: verify_application_health
      command: |
        curl -sf https://api.virtengine.io/cosmos/base/tendermint/v1beta1/node_info
      retries: 5
      interval: 15s
