// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: virtengine/oracle/v1/service.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("virtengine/oracle/v1/service.proto", fileDescriptor_ca56b03dddd2491e)
}

var fileDescriptor_ca56b03dddd2491e = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0xcb, 0x2c, 0x2a,
	0x49, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0xd5, 0xcf, 0x2f, 0x4a, 0x4c, 0xce, 0x49, 0xd5, 0x2f, 0x33,
	0xd4, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12,
	0x41, 0xa8, 0xd1, 0x83, 0xa8, 0xd1, 0x2b, 0x33, 0x94, 0x12, 0x4f, 0xce, 0x2f, 0xce, 0xcd, 0x2f,
	0xd6, 0xcf, 0x2d, 0x4e, 0x07, 0x69, 0xc9, 0x2d, 0x4e, 0x87, 0x28, 0x97, 0x92, 0xc7, 0x6a, 0x64,
	0x6e, 0x71, 0x7a, 0x31, 0x44, 0x81, 0xd1, 0x6d, 0x46, 0x2e, 0x66, 0xdf, 0xe2, 0x74, 0xa1, 0x74,
	0x2e, 0x5e, 0xc7, 0x94, 0x94, 0x80, 0xa2, 0xcc, 0xe4, 0x54, 0xd7, 0xbc, 0x92, 0xa2, 0x4a, 0x21,
	0x35, 0x3d, 0x6c, 0x36, 0xe9, 0xf9, 0x16, 0xa7, 0xa3, 0xa8, 0x93, 0xd2, 0x23, 0x4e, 0x5d, 0x50,
	0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x50, 0x0a, 0x17, 0x4f, 0x68, 0x41, 0x4a, 0x62, 0x49,
	0x6a, 0x40, 0x62, 0x51, 0x62, 0x6e, 0xb1, 0x90, 0x2a, 0x4e, 0xfd, 0xc8, 0xca, 0xa4, 0x74, 0x89,
	0x52, 0x06, 0xb3, 0x45, 0x8a, 0xb5, 0xe1, 0xf9, 0x06, 0x2d, 0x46, 0xa7, 0x80, 0x13, 0x8f, 0xe4,
	0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f,
	0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0x32, 0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b,
	0xce, 0xcf, 0xd5, 0x47, 0x0a, 0x23, 0x24, 0x66, 0x71, 0x4a, 0xb6, 0x7e, 0x7a, 0xbe, 0x7e, 0x5e,
	0x7e, 0x0a, 0x52, 0xd0, 0x25, 0xb1, 0x81, 0x83, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1b,
	0xb8, 0xc2, 0x9c, 0xac, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// AddPriceEntry adds a new price entry for a denomination from an authorized source
	AddPriceEntry(ctx context.Context, in *MsgAddPriceEntry, opts ...grpc.CallOption) (*MsgAddPriceEntryResponse, error)
	// UpdateParams defines a governance operation for updating the x/wasm module
	// parameters. The authority is hard-coded to the x/gov module account.
	//
	// Since: akash v2.0.0
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddPriceEntry(ctx context.Context, in *MsgAddPriceEntry, opts ...grpc.CallOption) (*MsgAddPriceEntryResponse, error) {
	out := new(MsgAddPriceEntryResponse)
	err := c.cc.Invoke(ctx, "/virtengine.oracle.v1.Msg/AddPriceEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/virtengine.oracle.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// AddPriceEntry adds a new price entry for a denomination from an authorized source
	AddPriceEntry(context.Context, *MsgAddPriceEntry) (*MsgAddPriceEntryResponse, error)
	// UpdateParams defines a governance operation for updating the x/wasm module
	// parameters. The authority is hard-coded to the x/gov module account.
	//
	// Since: akash v2.0.0
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddPriceEntry(ctx context.Context, req *MsgAddPriceEntry) (*MsgAddPriceEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPriceEntry not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddPriceEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddPriceEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddPriceEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/virtengine.oracle.v1.Msg/AddPriceEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddPriceEntry(ctx, req.(*MsgAddPriceEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/virtengine.oracle.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "virtengine.oracle.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPriceEntry",
			Handler:    _Msg_AddPriceEntry_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "virtengine/oracle/v1/service.proto",
}
