# Copyright 2024 VirtEngine Contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: ml-inference-latency
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - virtengine
    labelSelectors:
      app: ml-scorer
  delay:
    latency: "500ms"
    jitter: "100ms"
    correlation: "25"
  duration: "30m"
