# Copyright 2024 VirtEngine Contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: validator-partition
  namespace: chaos-testing
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - virtengine
    labelSelectors:
      app: virtengine-validator
  direction: both
  target:
    mode: fixed
    value: "1"
  duration: "60s"
  scheduler:
    cron: "@every 6h"
