# Copyright 2024 VirtEngine Contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: provider-daemon-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - virtengine
    labelSelectors:
      app: provider-daemon
  scheduler:
    cron: "@every 4h"
