# Copyright 2024 VirtEngine Contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-pressure
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - virtengine
    labelSelectors:
      app: virtengine-node
  stressors:
    memory:
      workers: 4
      size: '256MB'
  duration: "5m"
  scheduler:
    cron: "@every 8h"
