# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: virtengine/base/resources/v1beta4/storage.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'virtengine/base/resources/v1beta4/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from virtengine.base.attributes.v1 import attribute_pb2 as virtengine_dot_base_dot_attributes_dot_v1_dot_attribute__pb2
from virtengine.base.resources.v1beta4 import resourcevalue_pb2 as virtengine_dot_base_dot_resources_dot_v1beta4_dot_resourcevalue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/virtengine/base/resources/v1beta4/storage.proto\x12!virtengine.base.resources.v1beta4\x1a\x14gogoproto/gogo.proto\x1a-virtengine/base/attributes/v1/attribute.proto\x1a\x35virtengine/base/resources/v1beta4/resourcevalue.proto\"\xff\x02\n\x07Storage\x12+\n\x04name\x18\x01 \x01(\tB\x17\xea\xde\x1f\x04name\xf2\xde\x1f\x0byaml:\"name\"R\x04name\x12i\n\x08quantity\x18\x02 \x01(\x0b\x32\x30.virtengine.base.resources.v1beta4.ResourceValueB\x1b\xc8\xde\x1f\x00\xea\xde\x1f\x04size\xf2\xde\x1f\x0byaml:\"size\"R\x08quantity\x12\xd5\x01\n\nattributes\x18\x03 \x03(\x0b\x32(.virtengine.base.attributes.v1.AttributeB\x8a\x01\xc8\xde\x1f\x00\xea\xde\x1f\x14\x61ttributes,omitempty\xf2\xde\x1f\x1byaml:\"attributes,omitempty\"\xaa\xdf\x1fKgithub.com/virtengine/virtengine/sdk/go/node/types/attributes/v1.AttributesR\nattributes:\x04\xe8\xa0\x1f\x01\x42\x46ZDgithub.com/virtengine/virtengine/sdk/go/node/types/resources/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'virtengine.base.resources.v1beta4.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDgithub.com/virtengine/virtengine/sdk/go/node/types/resources/v1beta4'
  _globals['_STORAGE'].fields_by_name['name']._loaded_options = None
  _globals['_STORAGE'].fields_by_name['name']._serialized_options = b'\352\336\037\004name\362\336\037\013yaml:\"name\"'
  _globals['_STORAGE'].fields_by_name['quantity']._loaded_options = None
  _globals['_STORAGE'].fields_by_name['quantity']._serialized_options = b'\310\336\037\000\352\336\037\004size\362\336\037\013yaml:\"size\"'
  _globals['_STORAGE'].fields_by_name['attributes']._loaded_options = None
  _globals['_STORAGE'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\024attributes,omitempty\362\336\037\033yaml:\"attributes,omitempty\"\252\337\037Kgithub.com/virtengine/virtengine/sdk/go/node/types/attributes/v1.Attributes'
  _globals['_STORAGE']._loaded_options = None
  _globals['_STORAGE']._serialized_options = b'\350\240\037\001'
  _globals['_STORAGE']._serialized_start=211
  _globals['_STORAGE']._serialized_end=594
# @@protoc_insertion_point(module_scope)
