# OSS-Fuzz Project Configuration for VirtEngine
# 
# This file configures the VirtEngine project for OSS-Fuzz continuous fuzzing.
# Place this file in oss-fuzz/projects/virtengine/project.yaml
#
# See: https://google.github.io/oss-fuzz/getting-started/new-project-guide/
#
# Task Reference: QUALITY-002 - Fuzz Testing Implementation

homepage: "https://github.com/virtengine/virtengine"
language: go
primary_contact: "security@virtengine.io"
auto_ccs:
  - "dev@virtengine.io"

# Fuzzing configuration
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz

# Sanitizers to run
sanitizers:
  - address
  - undefined
  - memory

# Architecture support
architectures:
  - x86_64

# Main repository  
main_repo: "https://github.com/virtengine/virtengine.git"

# Vendor status (for Go projects)
vendor: true

# Build settings
builds_per_day: 1

# Coverage configuration
coverage_extra_args: ""

# File bug reports automatically
file_github_issue: true
