name: "Deploy Region"
description: "Deploy VirtEngine infrastructure to a specific AWS region"

inputs:
  region:
    description: "AWS region to deploy to"
    required: true
  role_arn:
    description: "IAM role ARN for deployment"
    required: true
  terraform_version:
    description: "Terraform version"
    required: false
    default: "1.6.0"
  apply:
    description: "Whether to apply (true) or just plan (false)"
    required: false
    default: "false"

outputs:
  plan_exitcode:
    description: "Terraform plan exit code"
    value: ${{ steps.plan.outputs.exitcode }}
  cluster_endpoint:
    description: "EKS cluster endpoint"
    value: ${{ steps.outputs.outputs.cluster_endpoint }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        aws-region: ${{ inputs.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Init
      shell: bash
      working-directory: infra/terraform/regions/${{ inputs.region }}
      run: terraform init -input=false

    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: infra/terraform/regions/${{ inputs.region }}
      run: |
        terraform plan -out=tfplan -input=false -detailed-exitcode || exitcode=$?
        echo "exitcode=${exitcode:-0}" >> "$GITHUB_OUTPUT"

    - name: Terraform Apply
      if: ${{ inputs.apply == 'true' }}
      shell: bash
      working-directory: infra/terraform/regions/${{ inputs.region }}
      run: terraform apply -auto-approve -input=false tfplan

    - name: Collect Outputs
      id: outputs
      if: ${{ inputs.apply == 'true' }}
      shell: bash
      working-directory: infra/terraform/regions/${{ inputs.region }}
      run: |
        endpoint=$(terraform output -raw cluster_endpoint 2>/dev/null || echo "")
        echo "cluster_endpoint=${endpoint}" >> "$GITHUB_OUTPUT"

    - name: Smoke Test
      if: ${{ inputs.apply == 'true' }}
      shell: bash
      run: |
        chmod +x scripts/smoke-test.sh
        scripts/smoke-test.sh ${{ inputs.region }}
