# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from virtengine.downtimedetector.v1beta1 import query_pb2 as virtengine_dot_downtimedetector_dot_v1beta1_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service for the downtime detector module
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecoveredSinceDowntimeOfLength = channel.unary_unary(
                '/virtengine.downtimedetector.v1beta1.Query/RecoveredSinceDowntimeOfLength',
                request_serializer=virtengine_dot_downtimedetector_dot_v1beta1_dot_query__pb2.RecoveredSinceDowntimeOfLengthRequest.SerializeToString,
                response_deserializer=virtengine_dot_downtimedetector_dot_v1beta1_dot_query__pb2.RecoveredSinceDowntimeOfLengthResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service for the downtime detector module
    """

    def RecoveredSinceDowntimeOfLength(self, request, context):
        """RecoveredSinceDowntimeOfLength queries if the chain has recovered for a specified duration
        since experiencing downtime of a given length
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecoveredSinceDowntimeOfLength': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoveredSinceDowntimeOfLength,
                    request_deserializer=virtengine_dot_downtimedetector_dot_v1beta1_dot_query__pb2.RecoveredSinceDowntimeOfLengthRequest.FromString,
                    response_serializer=virtengine_dot_downtimedetector_dot_v1beta1_dot_query__pb2.RecoveredSinceDowntimeOfLengthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'virtengine.downtimedetector.v1beta1.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('virtengine.downtimedetector.v1beta1.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service for the downtime detector module
    """

    @staticmethod
    def RecoveredSinceDowntimeOfLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/virtengine.downtimedetector.v1beta1.Query/RecoveredSinceDowntimeOfLength',
            virtengine_dot_downtimedetector_dot_v1beta1_dot_query__pb2.RecoveredSinceDowntimeOfLengthRequest.SerializeToString,
            virtengine_dot_downtimedetector_dot_v1beta1_dot_query__pb2.RecoveredSinceDowntimeOfLengthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
