# ArgoCD App of Apps - Root Application
# This deploys all VirtEngine applications across environments
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtengine-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: virtengine
  source:
    repoURL: https://github.com/virtengine-network/virtengine.git
    targetRevision: HEAD
    path: infra/argocd/applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
