# ApplicationSet for VirtEngine Core Services
# Deploys services across all environments with environment-specific configs
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtengine-core
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # Environment generator
          - list:
              elements:
                - env: dev
                  cluster: https://virtengine-dev.us-west-2.eks.amazonaws.com
                  autoSync: true
                  prune: true
                - env: staging
                  cluster: https://virtengine-staging.us-west-2.eks.amazonaws.com
                  autoSync: true
                  prune: true
                - env: prod
                  cluster: https://virtengine-prod.us-west-2.eks.amazonaws.com
                  autoSync: false  # Manual sync for production
                  prune: false
          # Service generator
          - list:
              elements:
                - service: virtengine-node
                  namespace: virtengine
                - service: provider-daemon
                  namespace: virtengine
                - service: waldur
                  namespace: virtengine
                - service: portal
                  namespace: virtengine
                - service: kong
                  namespace: virtengine

  template:
    metadata:
      name: '{{service}}-{{env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{service}}'
        app.kubernetes.io/instance: '{{service}}-{{env}}'
        app.kubernetes.io/component: core
        environment: '{{env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: virtengine
      source:
        repoURL: https://github.com/virtengine-network/virtengine.git
        targetRevision: '{{env}}'  # Branch matches environment
        path: 'infra/kubernetes/overlays/{{env}}/{{service}}'
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: '{{prune}}'
          selfHeal: '{{autoSync}}'
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas  # Ignore replica changes from HPA
        - group: autoscaling
          kind: HorizontalPodAutoscaler
          jsonPointers:
            - /status
---
# ApplicationSet for Infrastructure Services
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtengine-infra
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: dev
                  cluster: https://virtengine-dev.us-west-2.eks.amazonaws.com
                  autoSync: true
                - env: staging
                  cluster: https://virtengine-staging.us-west-2.eks.amazonaws.com
                  autoSync: true
                - env: prod
                  cluster: https://virtengine-prod.us-west-2.eks.amazonaws.com
                  autoSync: false
          - list:
              elements:
                - service: external-secrets
                  namespace: external-secrets
                  chart: external-secrets
                  repoURL: https://charts.external-secrets.io
                  version: 0.9.13
                - service: aws-load-balancer-controller
                  namespace: kube-system
                  chart: aws-load-balancer-controller
                  repoURL: https://aws.github.io/eks-charts
                  version: 1.7.1
                - service: metrics-server
                  namespace: kube-system
                  chart: metrics-server
                  repoURL: https://kubernetes-sigs.github.io/metrics-server
                  version: 3.12.0
                - service: cluster-autoscaler
                  namespace: kube-system
                  chart: cluster-autoscaler
                  repoURL: https://kubernetes.github.io/autoscaler
                  version: 9.35.0

  template:
    metadata:
      name: '{{service}}-{{env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{service}}'
        app.kubernetes.io/component: infrastructure
        environment: '{{env}}'
    spec:
      project: virtengine
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          releaseName: '{{service}}'
          valueFiles:
            - $values/infra/kubernetes/overlays/{{env}}/helm-values/{{service}}.yaml
      sources:
        - repoURL: '{{repoURL}}'
          chart: '{{chart}}'
          targetRevision: '{{version}}'
          helm:
            releaseName: '{{service}}'
            valueFiles:
              - $values/infra/kubernetes/overlays/{{env}}/helm-values/{{service}}.yaml
        - repoURL: https://github.com/virtengine-network/virtengine.git
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: '{{autoSync}}'
        syncOptions:
          - CreateNamespace=true
---
# ApplicationSet for Monitoring Stack
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtengine-monitoring
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://virtengine-dev.us-west-2.eks.amazonaws.com
          - env: staging
            cluster: https://virtengine-staging.us-west-2.eks.amazonaws.com
          - env: prod
            cluster: https://virtengine-prod.us-west-2.eks.amazonaws.com

  template:
    metadata:
      name: 'monitoring-{{env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: monitoring
        app.kubernetes.io/component: observability
        environment: '{{env}}'
    spec:
      project: virtengine
      source:
        repoURL: https://github.com/virtengine-network/virtengine.git
        targetRevision: HEAD
        path: 'infra/kubernetes/overlays/{{env}}/monitoring'
      destination:
        server: '{{cluster}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Large CRDs need server-side apply
