"use strict";

const assert = require("assert").strict;
const { parseAcceptance, validateCandidatePlan, verifyAcceptedPayload } = require("./preflight-integration-candidate.cjs");

const sha = (character) => character.repeat(40);
function fixture() {
  return {
    canonical_head: sha("a"), candidate_head: sha("b"),
    accepted_payloads: [{ thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }],
    contained_producer_commits: [{ thread: "T1", commit: sha("d") }],
  };
}
function options() {
  return { acceptanceCommitted: true, isAncestor: (ancestor, descendant) => [[sha("a"), sha("b")], [sha("c"), sha("b")], [sha("d"), sha("c")]].some(([left, right]) => left === ancestor && right === descendant), verifyAcceptedPayload: () => true };
}
const tests = [
  ["accepts an annotated handoff tag binding the payload", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify({ thread: "T1", checkpoint: "T1-09", branch: "ve/prototype-t1-identity", payload_head: entry.payload_sha }) } : { status: 0, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, runGit), true); }],
  ["rejects a tag peeling directly to the payload", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${entry.payload_sha}\ntype commit\ntag ${entry.tag}\n` } : { status: 0, stdout: `${entry.payload_sha}\n` }; assert.equal(verifyAcceptedPayload(".", entry, runGit), false); }],
  ["rejects a lightweight tag", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const runGit = () => ({ status: 0, stdout: "commit\n" }); assert.equal(verifyAcceptedPayload(".", entry, runGit), false); }],
  ["rejects a handoff binding another payload", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify({ thread: "T1", checkpoint: "T1-09", branch: "ve/prototype-t1-identity", payload_head: sha("e") }) } : { status: 0, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, runGit), false); }],
  ["rejects a handoff for another checkpoint or branch", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const document = { thread: "T1", checkpoint: "T1-08", branch: "ve/prototype-t1-identity", payload_head: entry.payload_sha }; const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify(document) } : { status: 0, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, runGit), false); document.checkpoint = "T1-09"; document.branch = "ve/prototype-t3-reliability"; assert.equal(verifyAcceptedPayload(".", entry, runGit), false); }],
  ["rejects a non-descendant handoff target", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify({ thread: "T1", checkpoint: "T1-09", branch: "ve/prototype-t1-identity", payload_head: entry.payload_sha }) } : { status: 1, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, runGit), false); }],
  ["rejects a missing or malformed committed handoff", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const base = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : { status: 1, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, base), false); const malformed = (_repo, args) => args[0] === "show" ? { status: 0, stdout: "not-json" } : base(_repo, args); assert.equal(verifyAcceptedPayload(".", entry, malformed), false); }],
  ["accepts the strict acceptance artifact schema", () => { const value = { schema_version: "virtengine.prototype.integration-candidate-acceptance/v1", status: "validated", base_sha: sha("a"), candidate_sha: sha("b"), accepted_payloads: [{ thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }] }; assert.doesNotThrow(() => parseAcceptance(JSON.stringify(value))); }],
  ["rejects informal acceptance summaries", () => { const value = { schema_version: "virtengine.prototype.live-integration-acceptance/v1", accepted_payloads: [{ thread: "T1", sha: sha("c") }] }; assert.throws(() => parseAcceptance(JSON.stringify(value))); }],
  ["accepts a canonical descendant with covered producer history", () => assert.doesNotThrow(() => validateCandidatePlan(fixture(), options()))],
  ["rejects a divergent candidate", () => { const value = options(); value.isAncestor = () => false; assert.throws(() => validateCandidatePlan(fixture(), value), /does not descend canonical/); }],
  ["rejects an uncommitted acceptance artifact", () => { const value = options(); value.acceptanceCommitted = false; assert.throws(() => validateCandidatePlan(fixture(), value), /not committed/); }],
  ["rejects duplicate accepted threads", () => { const value = fixture(); value.accepted_payloads.push(structuredClone(value.accepted_payloads[0])); assert.throws(() => validateCandidatePlan(value, options()), /threads must be unique/); }],
  ["rejects an unverified payload", () => { const value = options(); value.verifyAcceptedPayload = () => false; assert.throws(() => validateCandidatePlan(fixture(), value), /acceptance verification failed/); }],
  ["rejects uncovered producer history", () => { const value = fixture(); value.contained_producer_commits[0].thread = "T5"; assert.throws(() => validateCandidatePlan(value, options()), /unaccepted T5 commit/); }],
];
for (const [name, run] of tests) { run(); console.log(`ok - ${name}`); }