"use strict";

const assert = require("assert").strict;
const { buildCandidatePlan, parseAcceptance, resolvePublishedBranch, validateAcceptanceBoundary, validateCandidatePlan, verifyAcceptedPayload } = require("./preflight-integration-candidate.cjs");

const sha = (character) => character.repeat(40);
function fixture() {
  return {
    canonical_head: sha("a"), candidate_head: sha("b"),
    accepted_payloads: [{ thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }],
    contained_producer_commits: [{ thread: "T1", commit: sha("d") }],
  };
}
function options() {
  return { acceptanceCommitted: true, isAncestor: (ancestor, descendant) => [[sha("a"), sha("b")], [sha("c"), sha("b")], [sha("d"), sha("c")]].some(([left, right]) => left === ancestor && right === descendant), verifyAcceptedPayload: () => true };
}
function withPublishedTag(entry, runGit) {
  const tagRef = `refs/tags/${entry.tag}`;
  const tagObject = sha("f");
  return (repo, args) => args[0] === "ls-remote" ? { status: 0, stdout: `${tagObject}\t${tagRef}\n` }
    : args[0] === "rev-parse" && args.at(-1) === tagRef ? { status: 0, stdout: `${tagObject}\n` }
      : runGit(repo, args);
}
const tests = [
  ["accepts a published annotated handoff tag binding the payload", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const tagObject = sha("e"); const handoff = sha("d"); const tagRef = `refs/tags/${entry.tag}`; const runGit = (_repo, args) => args[0] === "ls-remote" ? { status: 0, stdout: `${tagObject}\t${tagRef}\n` } : args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" && args.at(-1) === tagRef ? { status: 0, stdout: `${tagObject}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify({ thread: "T1", checkpoint: "T1-09", branch: "ve/prototype-t1-identity", payload_head: entry.payload_sha }) } : { status: 0, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, runGit), true); }],
  ["rejects a local-only or stale checkpoint tag", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const tagRef = `refs/tags/${entry.tag}`; const localOnly = (_repo, args) => args[0] === "ls-remote" ? { status: 2, stdout: "" } : { status: 0, stdout: `${sha("e")}\n` }; assert.equal(verifyAcceptedPayload(".", entry, localOnly), false); const stale = (_repo, args) => args[0] === "ls-remote" ? { status: 0, stdout: `${sha("f")}\t${tagRef}\n` } : { status: 0, stdout: `${sha("e")}\n` }; assert.equal(verifyAcceptedPayload(".", entry, stale), false); }],
  ["rejects malformed or unexpected remote tag evidence", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const tagRef = `refs/tags/${entry.tag}`; for (const stdout of [`${sha("e")} refs/tags/${entry.tag}\n`, `${sha("e")}\t${tagRef}^{}\n`, `${sha("e")}\t${tagRef}\n${sha("e")}\t${tagRef}\n`]) { const runGit = (_repo, args) => args[0] === "ls-remote" ? { status: 0, stdout } : { status: 0, stdout: `${sha("e")}\n` }; assert.equal(verifyAcceptedPayload(".", entry, runGit), false); } }],
  ["rejects a tag peeling directly to the payload", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${entry.payload_sha}\ntype commit\ntag ${entry.tag}\n` } : { status: 0, stdout: `${entry.payload_sha}\n` }; assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, runGit)), false); }],
  ["rejects a lightweight tag", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const runGit = () => ({ status: 0, stdout: "commit\n" }); assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, runGit)), false); }],
  ["rejects a handoff binding another payload", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify({ thread: "T1", checkpoint: "T1-09", branch: "ve/prototype-t1-identity", payload_head: sha("e") }) } : { status: 0, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, runGit)), false); }],
  ["rejects a handoff for another checkpoint or branch", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const document = { thread: "T1", checkpoint: "T1-08", branch: "ve/prototype-t1-identity", payload_head: entry.payload_sha }; const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify(document) } : { status: 0, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, runGit)), false); document.checkpoint = "T1-09"; document.branch = "ve/prototype-t3-reliability"; assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, runGit)), false); }],
  ["rejects a non-descendant handoff target", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const runGit = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : args[0] === "show" ? { status: 0, stdout: JSON.stringify({ thread: "T1", checkpoint: "T1-09", branch: "ve/prototype-t1-identity", payload_head: entry.payload_sha }) } : { status: 1, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, runGit)), false); }],
  ["rejects a missing or malformed committed handoff", () => { const entry = { thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }; const handoff = sha("d"); const base = (_repo, args) => args[0] === "cat-file" && args[1] === "-t" ? { status: 0, stdout: "tag\n" } : args[0] === "cat-file" ? { status: 0, stdout: `object ${handoff}\ntype commit\ntag ${entry.tag}\n` } : args[0] === "rev-parse" ? { status: 0, stdout: `${handoff}\n` } : { status: 1, stdout: "" }; assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, base)), false); const malformed = (_repo, args) => args[0] === "show" ? { status: 0, stdout: "not-json" } : base(_repo, args); assert.equal(verifyAcceptedPayload(".", entry, withPublishedTag(entry, malformed)), false); }],
  ["accepts the strict acceptance artifact schema", () => { const value = { schema_version: "virtengine.prototype.integration-candidate-acceptance/v1", status: "validated", base_sha: sha("a"), candidate_sha: sha("b"), accepted_payloads: [{ thread: "T1", tag: "checkpoint/prototype-t1/t1-09", payload_sha: sha("c") }] }; assert.doesNotThrow(() => parseAcceptance(JSON.stringify(value))); }],
  ["rejects informal acceptance summaries", () => { const value = { schema_version: "virtengine.prototype.live-integration-acceptance/v1", accepted_payloads: [{ thread: "T1", sha: sha("c") }] }; assert.throws(() => parseAcceptance(JSON.stringify(value))); }],
  ["accepts a strict implementation-to-acceptance boundary", () => { const boundary = { canonical_head: sha("a"), candidate_sha: sha("b"), candidate_head: sha("c"), acceptance_path: "acceptance.json" }; const ancestry = new Set([`${sha("a")}:${sha("b")}`, `${sha("b")}:${sha("c")}`]); assert.doesNotThrow(() => validateAcceptanceBoundary(boundary, { isAncestor: (left, right) => ancestry.has(`${left}:${right}`), parents: () => [sha("b")], changedPaths: () => ["acceptance.json"] })); }],
  ["rejects a self-referential acceptance boundary", () => { const boundary = { canonical_head: sha("a"), candidate_sha: sha("b"), candidate_head: sha("b"), acceptance_path: "acceptance.json" }; assert.throws(() => validateAcceptanceBoundary(boundary, { isAncestor: () => true, parents: () => [sha("a")], changedPaths: () => ["acceptance.json"] }), /cannot self-reference/); }],
  ["rejects a merge or indirect acceptance commit", () => { const boundary = { canonical_head: sha("a"), candidate_sha: sha("b"), candidate_head: sha("c"), acceptance_path: "acceptance.json" }; assert.throws(() => validateAcceptanceBoundary(boundary, { isAncestor: () => true, parents: () => [sha("b"), sha("d")], changedPaths: () => ["acceptance.json"] }), /direct non-merge child/); assert.throws(() => validateAcceptanceBoundary(boundary, { isAncestor: () => true, parents: () => [sha("d")], changedPaths: () => ["acceptance.json"] }), /direct non-merge child/); }],
  ["rejects unrelated changes after the validated candidate", () => { const boundary = { canonical_head: sha("a"), candidate_sha: sha("b"), candidate_head: sha("c"), acceptance_path: "acceptance.json" }; assert.throws(() => validateAcceptanceBoundary(boundary, { isAncestor: () => true, parents: () => [sha("b")], changedPaths: () => ["acceptance.json", "app/app.go"] }), /changes paths other than/); }],
  ["rejects an acceptance commit outside candidate ancestry", () => { const boundary = { canonical_head: sha("a"), candidate_sha: sha("b"), candidate_head: sha("c"), acceptance_path: "acceptance.json" }; assert.throws(() => validateAcceptanceBoundary(boundary, { isAncestor: (left) => left === sha("a"), parents: () => [sha("b")], changedPaths: () => ["acceptance.json"] }), /does not descend the validated candidate/); }],
  ["pins acceptance reads to the resolved candidate head", () => { const calls = []; const acceptance = JSON.stringify({ schema_version: "virtengine.prototype.integration-candidate-acceptance/v1", status: "validated", base_sha: sha("a"), candidate_sha: sha("c"), accepted_payloads: [] }); const runGit = (_repo, args) => { calls.push(args); if (args[0] === "rev-parse" && args[1] === "canonical-ref^{commit}") return { status: 0, stdout: `${sha("a")}\n` }; if (args[0] === "rev-parse" && args[1] === "candidate-ref^{commit}") return { status: 0, stdout: `${sha("b")}\n` }; if (args[0] === "rev-parse") return { status: 0, stdout: `${sha("d")}\n` }; if (args[0] === "show" && args[1] === `${sha("b")}:acceptance.json`) return { status: 0, stdout: acceptance }; if (args[0] === "show") return { status: 0, stdout: `${sha("c")}\n` }; if (args[0] === "diff") return { status: 0, stdout: "acceptance.json\n" }; if (args[0] === "merge-base" && args[1] !== "--is-ancestor") return { status: 0, stdout: `${sha("a")}\n` }; return { status: 0, stdout: "" }; }; assert.doesNotThrow(() => buildCandidatePlan(".", "candidate-ref", "canonical-ref", "acceptance.json", [], runGit)); assert.deepEqual(calls.filter((args) => args.some((argument) => argument.includes("candidate-ref"))), [["rev-parse", "candidate-ref^{commit}"]]); }],
  ["resolves an exact published producer branch", () => { const branch = "ve/prototype-t2-product"; const branchRef = `refs/heads/${branch}`; const runGit = (_repo, args) => args[0] === "ls-remote" ? { status: 0, stdout: `${sha("a")}\t${branchRef}\r\n` } : { status: 0, stdout: `${sha("a")}\n` }; assert.equal(resolvePublishedBranch(".", branch, runGit), sha("a")); }],
  ["rejects stale or malformed producer branch evidence", () => { const branch = "ve/prototype-t2-product"; const branchRef = `refs/heads/${branch}`; const stale = (_repo, args) => args[0] === "ls-remote" ? { status: 0, stdout: `${sha("a")}\t${branchRef}\n` } : { status: 0, stdout: `${sha("b")}\n` }; assert.throws(() => resolvePublishedBranch(".", branch, stale), /is stale/); for (const stdout of ["", `${sha("a")} ${branchRef}\n`, `${sha("a")}\t${branchRef}\n${sha("a")}\t${branchRef}\n`]) { const malformed = (_repo, args) => args[0] === "ls-remote" ? { status: stdout ? 0 : 2, stdout } : { status: 0, stdout: `${sha("a")}\n` }; assert.throws(() => resolvePublishedBranch(".", branch, malformed), /is unavailable/); } }],
  ["accepts a canonical descendant with covered producer history", () => assert.doesNotThrow(() => validateCandidatePlan(fixture(), options()))],
  ["rejects a divergent candidate", () => { const value = options(); value.isAncestor = () => false; assert.throws(() => validateCandidatePlan(fixture(), value), /does not descend canonical/); }],
  ["rejects an uncommitted acceptance artifact", () => { const value = options(); value.acceptanceCommitted = false; assert.throws(() => validateCandidatePlan(fixture(), value), /not committed/); }],
  ["rejects duplicate accepted threads", () => { const value = fixture(); value.accepted_payloads.push(structuredClone(value.accepted_payloads[0])); assert.throws(() => validateCandidatePlan(value, options()), /threads must be unique/); }],
  ["rejects an unverified payload", () => { const value = options(); value.verifyAcceptedPayload = () => false; assert.throws(() => validateCandidatePlan(fixture(), value), /acceptance verification failed/); }],
  ["rejects uncovered producer history", () => { const value = fixture(); value.contained_producer_commits[0].thread = "T5"; assert.throws(() => validateCandidatePlan(value, options()), /unaccepted T5 commit/); }],
];
for (const [name, run] of tests) { run(); console.log(`ok - ${name}`); }