import type { IdentityState } from '@/lib/portal-adapter';

export const mockProviders = {
  virtengine1provider1xyz: {
    owner: 'virtengine1provider1xyz',
    attributes: [
      { key: 'name', value: 'CloudCore' },
      { key: 'description', value: 'High performance GPU cloud provider.' },
      { key: 'reputation', value: '92' },
      { key: 'verified', value: 'true' },
      { key: 'region', value: 'us-west,eu-west' },
    ],
    info: { website: 'https://cloudcore.example' },
    created_at: '2025-10-10T00:00:00Z',
  },
  virtengine1provider2xyz: {
    owner: 'virtengine1provider2xyz',
    attributes: [
      { key: 'name', value: 'DataNexus' },
      { key: 'description', value: 'Reliable CPU compute clusters.' },
      { key: 'reputation', value: '76' },
      { key: 'verified', value: 'true' },
      { key: 'region', value: 'us-east' },
    ],
    info: { website: 'https://datanexus.example' },
    created_at: '2025-09-14T00:00:00Z',
  },
  virtengine1provider3xyz: {
    owner: 'virtengine1provider3xyz',
    attributes: [
      { key: 'name', value: 'Storix' },
      { key: 'description', value: 'Durable storage and data services.' },
      { key: 'reputation', value: '64' },
      { key: 'verified', value: 'false' },
      { key: 'region', value: 'us-central,eu-central' },
    ],
    info: { website: 'https://storix.example' },
    created_at: '2025-08-02T00:00:00Z',
  },
} as const;

export const mockOfferings = [
  {
    id: { provider_address: 'virtengine1provider1xyz', sequence: 101 },
    provider_address: 'virtengine1provider1xyz',
    sequence: 101,
    name: 'NVIDIA A100 Cluster',
    description: 'High-performance GPU cluster for ML training.',
    state: 'active',
    category: 'gpu',
    version: '1.2.0',
    pricing: {
      model: 'hourly',
      base_price: '2500000',
      currency: 'uve',
      usage_rates: { gpu: '2500000', cpu: '500000' },
    },
    prices: [
      {
        resource_type: 'gpu',
        unit: 'hour',
        price: { denom: 'uve', amount: '2500000' },
        usd_reference: '2.5',
      },
      {
        resource_type: 'cpu',
        unit: 'hour',
        price: { denom: 'uve', amount: '500000' },
        usd_reference: '0.5',
      },
    ],
    tags: ['gpu', 'a100', 'ml'],
    regions: ['us-west', 'eu-west'],
    specifications: {
      cpu: '64',
      memory: '256',
      gpu_count: '4',
      storage: '2000',
    },
    total_order_count: 12,
    active_order_count: 4,
    identity_requirement: {
      min_score: 0,
      require_verified_email: false,
      require_mfa: false,
    },
    require_mfa_for_orders: false,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-06T10:00:00Z',
  },
  {
    id: { provider_address: 'virtengine1provider2xyz', sequence: 202 },
    provider_address: 'virtengine1provider2xyz',
    sequence: 202,
    name: 'EPYC Compute Pool',
    description: 'Balanced CPU workloads with fast networking.',
    state: 'active',
    category: 'compute',
    version: '3.0.1',
    pricing: {
      model: 'hourly',
      base_price: '450000',
      currency: 'uve',
      usage_rates: { cpu: '450000' },
    },
    prices: [
      {
        resource_type: 'cpu',
        unit: 'hour',
        price: { denom: 'uve', amount: '450000' },
        usd_reference: '0.45',
      },
    ],
    tags: ['cpu', 'compute'],
    regions: ['us-east'],
    specifications: {
      cpu: '32',
      memory: '128',
      storage: '1000',
    },
    total_order_count: 8,
    active_order_count: 2,
    identity_requirement: {
      min_score: 0,
      require_verified_email: false,
      require_mfa: false,
    },
    require_mfa_for_orders: false,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-02-04T10:00:00Z',
  },
  {
    id: { provider_address: 'virtengine1provider3xyz', sequence: 303 },
    provider_address: 'virtengine1provider3xyz',
    sequence: 303,
    name: 'NVMe Storage Vault',
    description: 'High-throughput storage for data-heavy workloads.',
    state: 'active',
    category: 'storage',
    version: '2.4.0',
    pricing: {
      model: 'hourly',
      base_price: '120000',
      currency: 'uve',
      usage_rates: { storage: '120000' },
    },
    prices: [
      {
        resource_type: 'storage',
        unit: 'gb-hour',
        price: { denom: 'uve', amount: '120000' },
        usd_reference: '0.12',
      },
    ],
    tags: ['storage', 'nvme'],
    regions: ['us-central', 'eu-central'],
    specifications: {
      storage: '5000',
      cpu: '8',
      memory: '32',
    },
    total_order_count: 5,
    active_order_count: 1,
    identity_requirement: {
      min_score: 0,
      require_verified_email: false,
      require_mfa: false,
    },
    require_mfa_for_orders: false,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-02-03T10:00:00Z',
  },
] as const;

export const mockIdentityState: Partial<IdentityState> = {
  isLoading: false,
  status: 'verified',
  score: {
    value: 72,
    tier: 'premium',
    computedAt: Date.now(),
    modelVersion: 'test-1',
    breakdown: {
      document: 18,
      facial: 18,
      metadata: 18,
      trust: 18,
    },
    blockHeight: 123456,
  },
  completedScopes: [{ type: 'email', completed: true, verifiedAt: Date.now() - 86400000 }],
  uploadHistory: [],
  verificationRecords: [],
  error: null,
};
