FROM golang:1.25.14-alpine@sha256:1ae0735f00daffa3aaf1363a5184c0d2dc55c78e3db4ec70241cdac97bf84b59 AS build

RUN apk add --no-cache ca-certificates git

WORKDIR /src
COPY go.mod go.sum ./
COPY sdk/go/go.mod sdk/go/go.sum sdk/go/
COPY sdk/specs/go.mod sdk/specs/
RUN go mod download

COPY . .

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ENV CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH}

RUN go build -trimpath -buildvcs=false -ldflags "-s -w" -o /out/virtengine ./cmd/virtengine

FROM alpine:3.20@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc
LABEL "org.opencontainers.image.source"="https://github.com/virtengine-network/node"

RUN apk add --no-cache bash ca-certificates curl jq && \
    addgroup -S virtengine && \
    adduser -S -G virtengine -u 10001 virtengine && \
    mkdir -p /var/lib/virtengine && \
    chown -R virtengine:virtengine /var/lib/virtengine

ENV HOME=/var/lib/virtengine
WORKDIR /var/lib/virtengine
VOLUME ["/var/lib/virtengine", "/tmp"]

COPY --from=build /out/virtengine /usr/local/bin/virtengine

USER 10001:10001

EXPOSE 26656 26657 26658 1317 9090 9091
