FROM node:20-alpine

WORKDIR /workspace/sdk/portal

RUN corepack enable

COPY sdk/portal/package.json ./
COPY sdk/portal/pnpm-lock.yaml ./

RUN pnpm install

COPY sdk/portal ./

EXPOSE 5173

CMD ["pnpm", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
