FROM golang:1.26.8-alpine@sha256:8ac98ca534ac3f51e1f420a1dd2c15e74c75cfa0f23f3ad27eb5d7236c349a0c AS build

RUN apk add --no-cache ca-certificates git

WORKDIR /src
COPY go.mod go.sum ./
COPY sdk/go/go.mod sdk/go/go.sum sdk/go/
COPY sdk/specs/go.mod sdk/specs/
RUN go mod download

COPY . .

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ENV CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH}

RUN go build -trimpath -buildvcs=false -ldflags "-s -w" -o /out/virtengine ./cmd/virtengine

FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
LABEL "org.opencontainers.image.source"="https://github.com/virtengine-network/node"

RUN apk upgrade --no-cache && apk add --no-cache bash ca-certificates curl jq && \
    addgroup -S virtengine && \
    adduser -S -G virtengine -u 10001 virtengine && \
    mkdir -p /var/lib/virtengine && \
    chown -R virtengine:virtengine /var/lib/virtengine

ENV HOME=/var/lib/virtengine
WORKDIR /var/lib/virtengine
VOLUME ["/var/lib/virtengine", "/tmp"]

COPY --from=build /out/virtengine /usr/local/bin/virtengine

USER 10001:10001

EXPOSE 26656 26657 26658 1317 9090 9091
