apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: virtengine

resources:
  - common-resources.yaml
  - config.yaml
  - secrets.yaml
  - monitoring.yaml
  - sgx-deployment.yaml
  - sev-deployment.yaml
