apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-bootstrap-metadata
  namespace: argocd
data:
  version: "v2.10.0"
  install_url: "https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/install.yaml"
  ha_install_url: "https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/ha/install.yaml"
  selected_profile: "ha"
