# ArgoCD Installation and Configuration
# Kustomization base for ArgoCD deployment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - install.yaml
  - ingress.yaml
  - projects/virtengine.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/ha/install.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-cmd-params-cm.yaml
