package v1beta4

const (
	VERIFICATION_METHOD_UNKNOWN         = VerificationMethod_VERIFICATION_METHOD_UNKNOWN
	VERIFICATION_METHOD_DNS_TXT         = VerificationMethod_VERIFICATION_METHOD_DNS_TXT
	VERIFICATION_METHOD_DNS_CNAME       = VerificationMethod_VERIFICATION_METHOD_DNS_CNAME
	VERIFICATION_METHOD_HTTP_WELL_KNOWN = VerificationMethod_VERIFICATION_METHOD_HTTP_WELL_KNOWN
)
