# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: virtengine/escrow/id/v1/id.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'virtengine/escrow/id/v1/id.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n virtengine/escrow/id/v1/id.proto\x12\x17virtengine.escrow.id.v1\x1a\x14gogoproto/gogo.proto\"\x90\x01\n\x07\x41\x63\x63ount\x12O\n\x05scope\x18\x01 \x01(\x0e\x32\x1e.virtengine.escrow.id.v1.ScopeB\x19\xea\xde\x1f\x05scope\xf2\xde\x1f\x0cyaml:\"scope\"R\x05scope\x12.\n\x03xid\x18\x02 \x01(\tB\x1c\xe2\xde\x1f\x03XID\xea\xde\x1f\x03xid\xf2\xde\x1f\nyaml:\"xid\"R\x03xid:\x04\x98\xa0\x1f\x01\"\x95\x01\n\x07Payment\x12T\n\x03\x61id\x18\x01 \x01(\x0b\x32 .virtengine.escrow.id.v1.AccountB \xc8\xde\x1f\x00\xe2\xde\x1f\x03\x41ID\xea\xde\x1f\x03\x61id\xf2\xde\x1f\nyaml:\"aid\"R\x03\x61id\x12.\n\x03xid\x18\x02 \x01(\tB\x1c\xe2\xde\x1f\x03XID\xea\xde\x1f\x03xid\xf2\xde\x1f\nyaml:\"xid\"R\x03xid:\x04\x98\xa0\x1f\x01*h\n\x05Scope\x12\x1d\n\x07invalid\x10\x00\x1a\x10\x8a\x9d \x0cScopeInvalid\x12#\n\ndeployment\x10\x01\x1a\x13\x8a\x9d \x0fScopeDeployment\x12\x15\n\x03\x62id\x10\x02\x1a\x0c\x8a\x9d \x08ScopeBid\x1a\x04\x88\xa3\x1e\x00\x42;Z9github.com/virtengine/virtengine/sdk/go/node/escrow/id/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'virtengine.escrow.id.v1.id_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/virtengine/virtengine/sdk/go/node/escrow/id/v1'
  _globals['_SCOPE']._loaded_options = None
  _globals['_SCOPE']._serialized_options = b'\210\243\036\000'
  _globals['_SCOPE'].values_by_name["invalid"]._loaded_options = None
  _globals['_SCOPE'].values_by_name["invalid"]._serialized_options = b'\212\235 \014ScopeInvalid'
  _globals['_SCOPE'].values_by_name["deployment"]._loaded_options = None
  _globals['_SCOPE'].values_by_name["deployment"]._serialized_options = b'\212\235 \017ScopeDeployment'
  _globals['_SCOPE'].values_by_name["bid"]._loaded_options = None
  _globals['_SCOPE'].values_by_name["bid"]._serialized_options = b'\212\235 \010ScopeBid'
  _globals['_ACCOUNT'].fields_by_name['scope']._loaded_options = None
  _globals['_ACCOUNT'].fields_by_name['scope']._serialized_options = b'\352\336\037\005scope\362\336\037\014yaml:\"scope\"'
  _globals['_ACCOUNT'].fields_by_name['xid']._loaded_options = None
  _globals['_ACCOUNT'].fields_by_name['xid']._serialized_options = b'\342\336\037\003XID\352\336\037\003xid\362\336\037\nyaml:\"xid\"'
  _globals['_ACCOUNT']._loaded_options = None
  _globals['_ACCOUNT']._serialized_options = b'\230\240\037\001'
  _globals['_PAYMENT'].fields_by_name['aid']._loaded_options = None
  _globals['_PAYMENT'].fields_by_name['aid']._serialized_options = b'\310\336\037\000\342\336\037\003AID\352\336\037\003aid\362\336\037\nyaml:\"aid\"'
  _globals['_PAYMENT'].fields_by_name['xid']._loaded_options = None
  _globals['_PAYMENT'].fields_by_name['xid']._serialized_options = b'\342\336\037\003XID\352\336\037\003xid\362\336\037\nyaml:\"xid\"'
  _globals['_PAYMENT']._loaded_options = None
  _globals['_PAYMENT']._serialized_options = b'\230\240\037\001'
  _globals['_SCOPE']._serialized_start=382
  _globals['_SCOPE']._serialized_end=486
  _globals['_ACCOUNT']._serialized_start=84
  _globals['_ACCOUNT']._serialized_end=228
  _globals['_PAYMENT']._serialized_start=231
  _globals['_PAYMENT']._serialized_end=380
# @@protoc_insertion_point(module_scope)
